# Generated by Django 4.2.14 on 2024-11-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_category_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
    ]
